# Generated by Django 5.1.1 on 2026-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapitoken',
            name='yandex_folder_id',
            field=models.CharField(blank=True, default='', help_text='Yandex Cloud Folder ID. If empty, uses YANDEX_FOLDER_ID from settings.', max_length=255),
        ),
    ]
