# Generated by Django 5.1.1 on 2026-04-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('analyze', 'Анализ текста'), ('fetch_url', 'Загрузка URL')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('input_text', models.TextField(blank=True, default='')),
                ('input_url', models.CharField(blank=True, default='', max_length=2000)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('summary_green', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_orange', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_red', models.PositiveIntegerField(blank=True, null=True)),
                ('paragraphs_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Логи запросов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='plain_langu_created_2f236e_idx'), models.Index(fields=['user', '-created_at'], name='plain_langu_user_id_7ea659_idx'), models.Index(fields=['endpoint', '-created_at'], name='plain_langu_endpoin_a50ef2_idx')],
            },
        ),
    ]
